import { b, PALETTES, defineTemplate } from "../builder";
import type { TemplateDef } from "../types";

const annTimeline = [
  { time: "6:00 PM", title: "Welcome Toast", description: "" },
  { time: "7:00 PM", title: "Dinner", description: "" },
  { time: "8:30 PM", title: "Vow Renewal", description: "" },
  { time: "9:00 PM", title: "Dance", description: "" },
];

export const anniversaryTemplates: TemplateDef[] = [
  defineTemplate({
    id: "ann-pearl-25",
    name: "Silver Anniversary",
    category: "anniversary",
    featured: true,
    description: "25th anniversary in pearl tones with vow renewal program.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "25 Years", "Silver Anniversary"),
      b.message(PALETTES.pearl, "A quarter century of love. Join us as we celebrate."),
      b.quote(PALETTES.pearl, "Twenty-five years and forever to go."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl),
      b.timeline(PALETTES.pearl, annTimeline),
      b.gallery(PALETTES.pearl, 3),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "ann-gold-50",
    name: "Golden Anniversary",
    category: "anniversary",
    description: "50th anniversary celebration with photo timeline.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "50 Years", "Golden Anniversary"),
      b.message(PALETTES.ivory, "Half a century of love and family."),
      b.gallery(PALETTES.ivory, 3),
      b.quote(PALETTES.ivory, "Through every season, together."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, annTimeline),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "ann-monochrome",
    name: "Monochrome Vows",
    category: "anniversary",
    description: "Modern monochrome anniversary with vow renewal.",
    palette: PALETTES.monoBlack,
    blocks: [
      b.cover(PALETTES.monoBlack, "Renewing Our Vows", "Anniversary"),
      b.quote(PALETTES.monoBlack, "I'd choose you all over again."),
      b.message(PALETTES.monoBlack, "Witness our love, renewed."),
      b.countdown(PALETTES.monoBlack, "flip"),
      b.location(PALETTES.monoBlack),
      b.timeline(PALETTES.monoBlack, annTimeline),
      b.rsvp(PALETTES.monoBlack),
    ],
  }),
  defineTemplate({
    id: "ann-blush-romance",
    name: "Blush Romance",
    category: "anniversary",
    description: "Romantic blush palette anniversary.",
    palette: PALETTES.blush,
    blocks: [
      b.cover(PALETTES.blush, "Our Anniversary", "Forever and ever"),
      b.separator(PALETTES.blush, "hearts"),
      b.message(PALETTES.blush, "Years pass. Love stays."),
      b.gallery(PALETTES.blush, 3),
      b.countdown(PALETTES.blush),
      b.location(PALETTES.blush),
      b.timeline(PALETTES.blush, annTimeline),
      b.rsvp(PALETTES.blush),
    ],
  }),
  defineTemplate({
    id: "ann-sage-garden",
    name: "Garden Anniversary",
    category: "anniversary",
    description: "Outdoor garden anniversary brunch.",
    palette: PALETTES.sage,
    blocks: [
      b.cover(PALETTES.sage, "Our Garden", "Anniversary brunch"),
      b.separator(PALETTES.sage, "floral"),
      b.message(PALETTES.sage, "Among the leaves where it all began."),
      b.countdown(PALETTES.sage),
      b.location(PALETTES.sage),
      b.timeline(PALETTES.sage, annTimeline),
      b.gallery(PALETTES.sage, 3),
      b.rsvp(PALETTES.sage),
    ],
  }),
  defineTemplate({
    id: "ann-cinematic",
    name: "Cinematic Anniversary",
    category: "anniversary",
    description: "Hero video and music for a cinematic celebration.",
    palette: PALETTES.midnight,
    blocks: [
      b.heroVideo(PALETTES.midnight, "Our Story", "Anniversary"),
      b.music(PALETTES.midnight, "Our Song"),
      b.message(PALETTES.midnight, "Press play on our love story."),
      b.gallery(PALETTES.midnight, 3),
      b.countdown(PALETTES.midnight, "flip"),
      b.location(PALETTES.midnight),
      b.timeline(PALETTES.midnight, annTimeline),
      b.rsvp(PALETTES.midnight),
    ],
  }),
  defineTemplate({
    id: "ann-charcoal-modern",
    name: "Modern Anniversary",
    category: "anniversary",
    description: "Editorial-style anniversary invite.",
    palette: PALETTES.charcoal,
    blocks: [
      b.cover(PALETTES.charcoal, "Anniversary", "Still"),
      b.marquee(PALETTES.charcoal, "★ STILL IN LOVE ★ STILL IN LOVE ★"),
      b.message(PALETTES.charcoal, "Join us for an intimate evening."),
      b.countdown(PALETTES.charcoal),
      b.location(PALETTES.charcoal),
      b.timeline(PALETTES.charcoal, annTimeline),
      b.rsvp(PALETTES.charcoal),
    ],
  }),
  defineTemplate({
    id: "ann-white-minimal",
    name: "Minimal Anniversary",
    category: "anniversary",
    description: "Quiet, white minimalist anniversary.",
    palette: PALETTES.monoWhite,
    blocks: [
      b.cover(PALETTES.monoWhite, "Anniversary", ""),
      b.text(PALETTES.monoWhite, "An intimate dinner with our closest."),
      b.countdown(PALETTES.monoWhite, "minimal"),
      b.location(PALETTES.monoWhite),
      b.rsvp(PALETTES.monoWhite),
    ],
  }),
  defineTemplate({
    id: "ann-throwback",
    name: "Throwback Anniversary",
    category: "anniversary",
    description: "Photo-heavy anniversary tribute.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "Years Together", "Anniversary"),
      b.gallery(PALETTES.ivory, 3),
      b.quote(PALETTES.ivory, "Look at all this we made."),
      b.message(PALETTES.ivory, "Come laugh, cry, and celebrate."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, annTimeline),
      b.gallery(PALETTES.ivory, 2),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "ann-vow-renewal",
    name: "Vow Renewal",
    category: "anniversary",
    description: "Formal vow renewal ceremony invitation.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "Vow Renewal", "We do, again"),
      b.quote(PALETTES.pearl, "I'd marry you a thousand times."),
      b.message(PALETTES.pearl, "Witness our vows, renewed."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl),
      b.timeline(PALETTES.pearl, annTimeline),
      b.dressCode(PALETTES.pearl, [{ hex: "#fafaf7", name: "White" }]),
      b.rsvp(PALETTES.pearl),
    ],
  }),
];
