import { b, PALETTES, defineTemplate } from "../builder";
import type { TemplateDef } from "../types";

const showerTimeline = [
  { time: "2:00 PM", title: "Welcome Tea", description: "" },
  { time: "2:30 PM", title: "Games", description: "" },
  { time: "3:30 PM", title: "Gift Opening", description: "" },
  { time: "4:30 PM", title: "Cake & Photos", description: "" },
];

export const babyShowerTemplates: TemplateDef[] = [
  defineTemplate({
    id: "bs-blush-girl",
    name: "Blush Baby Girl",
    category: "baby_shower",
    featured: true,
    description: "Sweet blush palette for a baby girl shower.",
    palette: PALETTES.blush,
    blocks: [
      b.cover(PALETTES.blush, "Baby Shower", "It's a girl"),
      b.separator(PALETTES.blush, "hearts"),
      b.message(PALETTES.blush, "Tiny shoes, big love. Join us!"),
      b.countdown(PALETTES.blush),
      b.location(PALETTES.blush),
      b.timeline(PALETTES.blush, showerTimeline),
      b.giftRegistry(PALETTES.blush),
      b.gallery(PALETTES.blush, 2),
      b.rsvp(PALETTES.blush),
    ],
  }),
  defineTemplate({
    id: "bs-sage-boy",
    name: "Sage Baby Boy",
    category: "baby_shower",
    description: "Earthy sage palette for a baby boy shower.",
    palette: PALETTES.sage,
    blocks: [
      b.cover(PALETTES.sage, "Baby Shower", "It's a boy"),
      b.separator(PALETTES.sage, "floral"),
      b.message(PALETTES.sage, "Little adventures await. Join us!"),
      b.countdown(PALETTES.sage),
      b.location(PALETTES.sage),
      b.timeline(PALETTES.sage, showerTimeline),
      b.giftRegistry(PALETTES.sage),
      b.rsvp(PALETTES.sage),
    ],
  }),
  defineTemplate({
    id: "bs-neutral-pearl",
    name: "Neutral Pearl",
    category: "baby_shower",
    description: "Gender-neutral pearl palette baby shower.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "Baby on the Way", "Shower celebration"),
      b.message(PALETTES.pearl, "We can't wait to meet baby. Join us!"),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl),
      b.timeline(PALETTES.pearl, showerTimeline),
      b.giftRegistry(PALETTES.pearl),
      b.gallery(PALETTES.pearl, 2),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "bs-mono-modern",
    name: "Modern Monochrome",
    category: "baby_shower",
    description: "Modern black & white shower for any baby.",
    palette: PALETTES.monoBlack,
    blocks: [
      b.cover(PALETTES.monoBlack, "Baby Shower", ""),
      b.message(PALETTES.monoBlack, "A modern celebration of new life."),
      b.countdown(PALETTES.monoBlack),
      b.location(PALETTES.monoBlack),
      b.timeline(PALETTES.monoBlack, showerTimeline),
      b.giftRegistry(PALETTES.monoBlack),
      b.rsvp(PALETTES.monoBlack),
    ],
  }),
  defineTemplate({
    id: "bs-virtual",
    name: "Virtual Shower",
    category: "baby_shower",
    description: "Online baby shower with embed link.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "Virtual Shower", "Join from anywhere"),
      b.text(PALETTES.ivory, "Link will be shared on the day."),
      b.countdown(PALETTES.ivory),
      b.timeline(PALETTES.ivory, showerTimeline),
      b.giftRegistry(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "bs-twin-shower",
    name: "Twin Shower",
    category: "baby_shower",
    description: "For expecting twins — double everything.",
    palette: PALETTES.blush,
    blocks: [
      b.cover(PALETTES.blush, "Twin Shower", "Two on the way"),
      b.message(PALETTES.blush, "Double the joy, double the diapers."),
      b.countdown(PALETTES.blush),
      b.location(PALETTES.blush),
      b.timeline(PALETTES.blush, showerTimeline),
      b.giftRegistry(PALETTES.blush),
      b.giftRegistry(PALETTES.blush),
      b.rsvp(PALETTES.blush),
    ],
  }),
  defineTemplate({
    id: "bs-garden-tea",
    name: "Garden Tea",
    category: "baby_shower",
    description: "Outdoor garden tea-themed shower.",
    palette: PALETTES.sage,
    blocks: [
      b.cover(PALETTES.sage, "Garden Tea", "Baby shower"),
      b.separator(PALETTES.sage, "floral"),
      b.message(PALETTES.sage, "Tea, sandwiches, and a tiny new arrival."),
      b.countdown(PALETTES.sage),
      b.location(PALETTES.sage),
      b.timeline(PALETTES.sage, showerTimeline),
      b.gallery(PALETTES.sage, 3),
      b.giftRegistry(PALETTES.sage),
      b.rsvp(PALETTES.sage),
    ],
  }),
  defineTemplate({
    id: "bs-minimal-white",
    name: "White Minimal",
    category: "baby_shower",
    description: "Clean, all-white minimalist baby shower.",
    palette: PALETTES.monoWhite,
    blocks: [
      b.cover(PALETTES.monoWhite, "Baby Shower", ""),
      b.text(PALETTES.monoWhite, "Brunch at our home."),
      b.countdown(PALETTES.monoWhite, "minimal"),
      b.location(PALETTES.monoWhite),
      b.giftRegistry(PALETTES.monoWhite),
      b.rsvp(PALETTES.monoWhite),
    ],
  }),
  defineTemplate({
    id: "bs-storybook",
    name: "Storybook Shower",
    category: "baby_shower",
    description: "Bring a book instead of a card — storybook themed.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "Storybook Shower", "Bring a book"),
      b.quote(PALETTES.ivory, "And the adventure begins…"),
      b.message(PALETTES.ivory, "In lieu of a card, please bring your favorite children's book."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, showerTimeline),
      b.giftRegistry(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "bs-charcoal-cool",
    name: "Cool Charcoal",
    category: "baby_shower",
    description: "Modern charcoal palette for a cool, contemporary shower.",
    palette: PALETTES.charcoal,
    blocks: [
      b.cover(PALETTES.charcoal, "Baby Shower", "Coming soon"),
      b.text(PALETTES.charcoal, "An afternoon to celebrate the next chapter."),
      b.countdown(PALETTES.charcoal),
      b.location(PALETTES.charcoal),
      b.timeline(PALETTES.charcoal, showerTimeline),
      b.giftRegistry(PALETTES.charcoal),
      b.rsvp(PALETTES.charcoal),
    ],
  }),
];
