import { b, PALETTES, defineTemplate } from "../builder";
import type { TemplateDef } from "../types";

const partyTimeline = [
  { time: "5:00 PM", title: "Doors Open", description: "" },
  { time: "6:00 PM", title: "Dinner & Toast", description: "" },
  { time: "7:30 PM", title: "Cake & Speeches", description: "" },
  { time: "8:00 PM", title: "Dance Floor", description: "" },
];

export const birthdayTemplates: TemplateDef[] = [
  defineTemplate({
    id: "bday-mono-bash",
    name: "Mono Bash",
    category: "birthday",
    featured: true,
    description: "Bold monochrome birthday with marquee and gallery.",
    palette: PALETTES.monoBlack,
    blocks: [
      b.cover(PALETTES.monoBlack, "Birthday Bash", "Let's celebrate"),
      b.marquee(PALETTES.monoBlack, "★ HAPPY BIRTHDAY ★ HAPPY BIRTHDAY ★"),
      b.message(PALETTES.monoBlack, "Another year, another reason to gather."),
      b.countdown(PALETTES.monoBlack, "flip"),
      b.location(PALETTES.monoBlack),
      b.timeline(PALETTES.monoBlack, partyTimeline),
      b.gallery(PALETTES.monoBlack, 3),
      b.giftRegistry(PALETTES.monoBlack),
      b.rsvp(PALETTES.monoBlack),
    ],
  }),
  defineTemplate({
    id: "bday-blush-sweet",
    name: "Sweet Blush",
    category: "birthday",
    description: "Soft and sweet — perfect for milestone birthdays.",
    palette: PALETTES.blush,
    blocks: [
      b.cover(PALETTES.blush, "Sweet Birthday", "Cake & confetti"),
      b.separator(PALETTES.blush, "hearts"),
      b.message(PALETTES.blush, "Join me for a sweet, sweet day."),
      b.countdown(PALETTES.blush),
      b.location(PALETTES.blush),
      b.timeline(PALETTES.blush, partyTimeline),
      b.gallery(PALETTES.blush, 3),
      b.dressCode(PALETTES.blush, [{ hex: "#f5e6e0", name: "Blush" }, { hex: "#d4a5a5", name: "Rose" }]),
      b.rsvp(PALETTES.blush),
    ],
  }),
  defineTemplate({
    id: "bday-midnight-club",
    name: "Midnight Club",
    category: "birthday",
    featured: true,
    description: "Late-night birthday with hero video and music.",
    palette: PALETTES.midnight,
    blocks: [
      b.heroVideo(PALETTES.midnight, "Tonight", "We dance"),
      b.music(PALETTES.midnight),
      b.message(PALETTES.midnight, "Pull up. Dress sharp. Stay late."),
      b.countdown(PALETTES.midnight, "flip"),
      b.location(PALETTES.midnight),
      b.dressCode(PALETTES.midnight, [{ hex: "#000000", name: "All Black" }]),
      b.rsvp(PALETTES.midnight),
    ],
  }),
  defineTemplate({
    id: "bday-kids-joy",
    name: "Kids' Joy",
    category: "birthday",
    description: "Playful kids birthday with FAQ and gift list.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "Birthday Party!", "Bring your party hat"),
      b.text(PALETTES.ivory, "Games, cake, and lots of fun."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, partyTimeline),
      b.gallery(PALETTES.ivory, 2),
      b.giftRegistry(PALETTES.ivory),
      b.faq(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "bday-charcoal-supper",
    name: "Supper Club",
    category: "birthday",
    description: "Intimate dinner-party birthday for adults.",
    palette: PALETTES.charcoal,
    blocks: [
      b.cover(PALETTES.charcoal, "Supper Club", "An intimate birthday dinner"),
      b.quote(PALETTES.charcoal, "Good food. Good people. Good life."),
      b.message(PALETTES.charcoal, "An evening of long table dining."),
      b.countdown(PALETTES.charcoal),
      b.location(PALETTES.charcoal),
      b.timeline(PALETTES.charcoal, partyTimeline),
      b.dressCode(PALETTES.charcoal, [{ hex: "#1f1f1f", name: "Smart Casual" }]),
      b.rsvp(PALETTES.charcoal),
    ],
  }),
  defineTemplate({
    id: "bday-sage-brunch",
    name: "Garden Brunch",
    category: "birthday",
    description: "Daytime garden brunch birthday.",
    palette: PALETTES.sage,
    blocks: [
      b.cover(PALETTES.sage, "Birthday Brunch", "Bottomless mimosas"),
      b.separator(PALETTES.sage, "floral"),
      b.message(PALETTES.sage, "Mid-morning sun, garden table."),
      b.countdown(PALETTES.sage),
      b.location(PALETTES.sage),
      b.timeline(PALETTES.sage, partyTimeline),
      b.gallery(PALETTES.sage, 3),
      b.rsvp(PALETTES.sage),
    ],
  }),
  defineTemplate({
    id: "bday-pearl-milestone",
    name: "Milestone Pearl",
    category: "birthday",
    description: "Elegant milestone birthday (50, 60, 70+).",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "A Milestone", "Celebrating a life well lived"),
      b.message(PALETTES.pearl, "Please join us for a celebration of years and love."),
      b.gallery(PALETTES.pearl, 3),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl),
      b.timeline(PALETTES.pearl, partyTimeline),
      b.giftRegistry(PALETTES.pearl),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "bday-white-minimal",
    name: "White Minimal",
    category: "birthday",
    description: "Just the essentials — clean, white, modern.",
    palette: PALETTES.monoWhite,
    blocks: [
      b.cover(PALETTES.monoWhite, "Birthday", ""),
      b.text(PALETTES.monoWhite, "Drinks at 7. Dinner at 8."),
      b.countdown(PALETTES.monoWhite, "minimal"),
      b.location(PALETTES.monoWhite),
      b.rsvp(PALETTES.monoWhite),
    ],
  }),
  defineTemplate({
    id: "bday-cinematic",
    name: "Cinematic Birthday",
    category: "birthday",
    description: "Hero video birthday teaser with social links.",
    palette: PALETTES.midnight,
    blocks: [
      b.heroVideo(PALETTES.midnight, "It's My Birthday", "Press play"),
      b.message(PALETTES.midnight, "An evening built like a film."),
      b.countdown(PALETTES.midnight, "flip"),
      b.location(PALETTES.midnight),
      b.timeline(PALETTES.midnight, partyTimeline),
      b.gallery(PALETTES.midnight, 3),
      b.socials(PALETTES.midnight),
      b.rsvp(PALETTES.midnight),
    ],
  }),
  defineTemplate({
    id: "bday-throwback",
    name: "Throwback",
    category: "birthday",
    description: "Photo-heavy birthday celebrating memories.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "A Life in Photos", "Throwback Birthday"),
      b.gallery(PALETTES.ivory, 3),
      b.quote(PALETTES.ivory, "All these memories. All these years."),
      b.message(PALETTES.ivory, "Come reminisce, laugh, and celebrate."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, partyTimeline),
      b.gallery(PALETTES.ivory, 2),
      b.rsvp(PALETTES.ivory),
    ],
  }),
];
