import { b, PALETTES, defineTemplate } from "../builder";
import type { TemplateDef } from "../types";

const ct = [
  { time: "9:30 AM", title: "Guest Arrival", description: "" },
  { time: "10:00 AM", title: "Holy Mass & Christening", description: "" },
  { time: "11:30 AM", title: "Photo Session", description: "" },
  { time: "12:00 PM", title: "Reception", description: "" },
];

export const christeningTemplates: TemplateDef[] = [
  defineTemplate({
    id: "chr-pearl-blessing",
    name: "Pearl Blessing",
    category: "christening",
    featured: true,
    description: "Soft pearl tones for a sacred christening day.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "A Blessed Beginning", "Christening Celebration"),
      b.message(PALETTES.pearl, "We joyfully invite you to the christening of our little one."),
      b.quote(PALETTES.pearl, "Suffer the little children to come unto me."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl, "Parish Church"),
      b.timeline(PALETTES.pearl, ct),
      b.gallery(PALETTES.pearl, 3),
      b.dressCode(PALETTES.pearl, [{ hex: "#fafaf7", name: "White" }]),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "chr-ivory-classic",
    name: "Ivory Classic",
    category: "christening",
    description: "Traditional christening invitation with full reception details.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "Christening", "By the grace of God"),
      b.message(PALETTES.ivory, "Please join us in welcoming our child into the family of faith."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, ct),
      b.gallery(PALETTES.ivory, 2),
      b.giftRegistry(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "chr-blush-baby",
    name: "Blush Baby",
    category: "christening",
    description: "Tender blush palette ideal for baby girls.",
    palette: PALETTES.blush,
    blocks: [
      b.cover(PALETTES.blush, "Our Little Angel", "Christening Day"),
      b.separator(PALETTES.blush, "hearts"),
      b.message(PALETTES.blush, "A tiny life. A great love. A blessed day."),
      b.countdown(PALETTES.blush),
      b.location(PALETTES.blush),
      b.timeline(PALETTES.blush, ct),
      b.gallery(PALETTES.blush, 2),
      b.dressCode(PALETTES.blush, [{ hex: "#f5e6e0", name: "Blush" }]),
      b.rsvp(PALETTES.blush),
    ],
  }),
  defineTemplate({
    id: "chr-sage-grace",
    name: "Sage Grace",
    category: "christening",
    description: "Calm sage palette for outdoor or garden christenings.",
    palette: PALETTES.sage,
    blocks: [
      b.cover(PALETTES.sage, "Grace & Faith", "A blessing day"),
      b.separator(PALETTES.sage, "floral"),
      b.message(PALETTES.sage, "We give thanks and invite you to share our joy."),
      b.countdown(PALETTES.sage),
      b.location(PALETTES.sage),
      b.timeline(PALETTES.sage, ct),
      b.gallery(PALETTES.sage, 3),
      b.rsvp(PALETTES.sage),
    ],
  }),
  defineTemplate({
    id: "chr-mono-sacred",
    name: "Sacred Monochrome",
    category: "christening",
    description: "Refined black & white christening — formal and elegant.",
    palette: PALETTES.monoBlack,
    blocks: [
      b.cover(PALETTES.monoBlack, "Christening", ""),
      b.quote(PALETTES.monoBlack, "Let the children come to me."),
      b.message(PALETTES.monoBlack, "We invite you to a sacred celebration."),
      b.countdown(PALETTES.monoBlack),
      b.location(PALETTES.monoBlack),
      b.timeline(PALETTES.monoBlack, ct),
      b.dressCode(PALETTES.monoBlack, [{ hex: "#ffffff", name: "Sunday Best" }]),
      b.rsvp(PALETTES.monoBlack),
    ],
  }),
  defineTemplate({
    id: "chr-twins",
    name: "Twin Blessings",
    category: "christening",
    description: "Built for twins — dual hero, two galleries, one celebration.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "Twin Blessings", "Double the joy"),
      b.message(PALETTES.ivory, "Two hearts, one celebration."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, ct),
      b.gallery(PALETTES.ivory, 2),
      b.gallery(PALETTES.ivory, 2),
      b.giftRegistry(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "chr-charcoal-modern",
    name: "Modern Christening",
    category: "christening",
    description: "Contemporary monochrome layout for a modern family.",
    palette: PALETTES.charcoal,
    blocks: [
      b.cover(PALETTES.charcoal, "A New Soul", "Welcome"),
      b.text(PALETTES.charcoal, "Join us as we welcome our newest family member."),
      b.countdown(PALETTES.charcoal),
      b.location(PALETTES.charcoal),
      b.timeline(PALETTES.charcoal, ct),
      b.gallery(PALETTES.charcoal, 3),
      b.rsvp(PALETTES.charcoal),
    ],
  }),
  defineTemplate({
    id: "chr-white-minimal",
    name: "White Minimal",
    category: "christening",
    description: "All-white minimalist christening invitation.",
    palette: PALETTES.monoWhite,
    blocks: [
      b.cover(PALETTES.monoWhite, "Christening", ""),
      b.text(PALETTES.monoWhite, "A small gathering after the holy mass."),
      b.countdown(PALETTES.monoWhite, "minimal"),
      b.location(PALETTES.monoWhite),
      b.rsvp(PALETTES.monoWhite),
    ],
  }),
  defineTemplate({
    id: "chr-godparents-honor",
    name: "Godparents Honor",
    category: "christening",
    description: "Showcases godparents through entourage list (custom).",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "Christening", "Honoring our godparents"),
      b.message(PALETTES.pearl, "We are blessed to walk this journey with you."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl),
      b.entourage(PALETTES.pearl, "custom", "Godparents"),
      b.timeline(PALETTES.pearl, ct),
      b.gallery(PALETTES.pearl, 2),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "chr-cinematic-blessing",
    name: "Cinematic Blessing",
    category: "christening",
    description: "Hero video, gentle music, and a story-style scroll.",
    palette: PALETTES.midnight,
    blocks: [
      b.heroVideo(PALETTES.midnight, "A Blessed Day", "Christening"),
      b.music(PALETTES.midnight, "Hymn"),
      b.message(PALETTES.midnight, "Witness this sacred moment with us."),
      b.countdown(PALETTES.midnight),
      b.location(PALETTES.midnight),
      b.timeline(PALETTES.midnight, ct),
      b.gallery(PALETTES.midnight, 3),
      b.rsvp(PALETTES.midnight),
    ],
  }),
];
