import { b, PALETTES, defineTemplate } from "../builder";
import type { TemplateDef } from "../types";

const corpAgenda = [
  { time: "6:00 PM", title: "Registration", description: "" },
  { time: "6:30 PM", title: "Welcome Address", description: "" },
  { time: "7:00 PM", title: "Keynote", description: "" },
  { time: "8:00 PM", title: "Dinner", description: "" },
  { time: "9:30 PM", title: "Awards", description: "" },
];

export const corporateTemplates: TemplateDef[] = [
  defineTemplate({
    id: "corp-annual-gala",
    name: "Annual Gala",
    category: "corporate",
    featured: true,
    description: "Black-tie gala with full agenda, dress code, FAQ.",
    palette: PALETTES.monoBlack,
    blocks: [
      b.cover(PALETTES.monoBlack, "Annual Gala", "An evening of excellence"),
      b.message(PALETTES.monoBlack, "We are pleased to invite you to our annual gala."),
      b.countdown(PALETTES.monoBlack, "flip"),
      b.location(PALETTES.monoBlack),
      b.timeline(PALETTES.monoBlack, corpAgenda),
      b.dressCode(PALETTES.monoBlack, [{ hex: "#000000", name: "Black Tie" }]),
      b.faq(PALETTES.monoBlack),
      b.rsvp(PALETTES.monoBlack),
    ],
  }),
  defineTemplate({
    id: "corp-product-launch",
    name: "Product Launch",
    category: "corporate",
    description: "Launch event with hero video and live stream link.",
    palette: PALETTES.charcoal,
    blocks: [
      b.heroVideo(PALETTES.charcoal, "The Launch", "A new chapter"),
      b.message(PALETTES.charcoal, "Be among the first to experience what's next."),
      b.countdown(PALETTES.charcoal, "flip"),
      b.location(PALETTES.charcoal),
      b.timeline(PALETTES.charcoal, corpAgenda),
      b.socials(PALETTES.charcoal),
      b.rsvp(PALETTES.charcoal),
    ],
  }),
  defineTemplate({
    id: "corp-conference",
    name: "Conference",
    category: "corporate",
    description: "Multi-track conference with full schedule and FAQ.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "The Conference", "Where ideas meet"),
      b.message(PALETTES.pearl, "Join industry leaders for a day of insight."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl, "Convention Center"),
      b.timeline(PALETTES.pearl, corpAgenda),
      b.faq(PALETTES.pearl),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "corp-holiday-party",
    name: "Holiday Party",
    category: "corporate",
    description: "Office holiday party with festive marquee.",
    palette: PALETTES.midnight,
    blocks: [
      b.cover(PALETTES.midnight, "Holiday Party", "Cheers to a great year"),
      b.marquee(PALETTES.midnight, "★ HAPPY HOLIDAYS ★ CHEERS ★"),
      b.message(PALETTES.midnight, "An evening to thank our team and partners."),
      b.countdown(PALETTES.midnight),
      b.location(PALETTES.midnight),
      b.timeline(PALETTES.midnight, corpAgenda),
      b.dressCode(PALETTES.midnight, [{ hex: "#0d1424", name: "Cocktail Attire" }]),
      b.rsvp(PALETTES.midnight),
    ],
  }),
  defineTemplate({
    id: "corp-vip-dinner",
    name: "VIP Dinner",
    category: "corporate",
    description: "Intimate executive dinner.",
    palette: PALETTES.charcoal,
    blocks: [
      b.cover(PALETTES.charcoal, "VIP Dinner", "By invitation only"),
      b.quote(PALETTES.charcoal, "An intimate evening for our most valued partners."),
      b.message(PALETTES.charcoal, "Please join us for an exclusive dinner."),
      b.countdown(PALETTES.charcoal),
      b.location(PALETTES.charcoal),
      b.dressCode(PALETTES.charcoal, [{ hex: "#1f1f1f", name: "Business Formal" }]),
      b.rsvp(PALETTES.charcoal),
    ],
  }),
  defineTemplate({
    id: "corp-awards-night",
    name: "Awards Night",
    category: "corporate",
    description: "Recognition ceremony with timeline and seating.",
    palette: PALETTES.monoBlack,
    blocks: [
      b.cover(PALETTES.monoBlack, "Awards Night", "Honoring excellence"),
      b.message(PALETTES.monoBlack, "Tonight we celebrate the very best."),
      b.countdown(PALETTES.monoBlack, "flip"),
      b.location(PALETTES.monoBlack),
      b.timeline(PALETTES.monoBlack, corpAgenda),
      b.dressCode(PALETTES.monoBlack, [{ hex: "#000000", name: "Black Tie" }]),
      b.rsvp(PALETTES.monoBlack),
    ],
  }),
  defineTemplate({
    id: "corp-grand-opening",
    name: "Grand Opening",
    category: "corporate",
    description: "Ribbon-cutting event with directions and FAQ.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "Grand Opening", "Doors open soon"),
      b.message(PALETTES.ivory, "We are honored to invite you to our grand opening."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, corpAgenda),
      b.gallery(PALETTES.ivory, 3),
      b.faq(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "corp-summit",
    name: "Executive Summit",
    category: "corporate",
    description: "High-level summit with agenda and contact card.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "Executive Summit", "Strategy and vision"),
      b.message(PALETTES.pearl, "A working session for senior leaders."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl),
      b.timeline(PALETTES.pearl, corpAgenda),
      b.faq(PALETTES.pearl),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "corp-fundraiser",
    name: "Fundraiser",
    category: "corporate",
    description: "Charity fundraiser with cause messaging and donation CTA.",
    palette: PALETTES.sage,
    blocks: [
      b.cover(PALETTES.sage, "For a Cause", "Charity Fundraiser"),
      b.quote(PALETTES.sage, "Together we can do more."),
      b.message(PALETTES.sage, "An evening to give back."),
      b.countdown(PALETTES.sage),
      b.location(PALETTES.sage),
      b.timeline(PALETTES.sage, corpAgenda),
      b.giftRegistry(PALETTES.sage),
      b.rsvp(PALETTES.sage),
    ],
  }),
  defineTemplate({
    id: "corp-minimal-meeting",
    name: "Minimal Meeting",
    category: "corporate",
    description: "Clean, no-fluff invite for board or team meetings.",
    palette: PALETTES.monoWhite,
    blocks: [
      b.cover(PALETTES.monoWhite, "Meeting", "Save the date"),
      b.text(PALETTES.monoWhite, "Agenda will be circulated 24h before."),
      b.countdown(PALETTES.monoWhite, "minimal"),
      b.location(PALETTES.monoWhite),
      b.rsvp(PALETTES.monoWhite),
    ],
  }),
];
