import { b, PALETTES, defineTemplate } from "../builder";
import type { TemplateDef } from "../types";

const debutTimeline = [
  { time: "5:00 PM", title: "Arrival & Cocktails", description: "Welcome reception" },
  { time: "6:00 PM", title: "Grand Entrance", description: "" },
  { time: "6:30 PM", title: "18 Roses", description: "" },
  { time: "7:15 PM", title: "18 Candles", description: "" },
  { time: "8:00 PM", title: "18 Treasures", description: "" },
  { time: "8:45 PM", title: "Dinner", description: "" },
  { time: "9:30 PM", title: "Party", description: "" },
];

export const debutTemplates: TemplateDef[] = [
  defineTemplate({
    id: "debut-monochrome-elegance",
    name: "Monochrome Elegance",
    category: "debut",
    description: "Black & white classic with formal 18 roses, candles, and treasures program.",
    palette: PALETTES.monoBlack,
    featured: true,
    blocks: [
      b.cover(PALETTES.monoBlack, "My Grand Debut", "You are cordially invited"),
      b.message(PALETTES.monoBlack, "On my eighteenth year, I invite you to share an evening of timeless elegance."),
      b.countdown(PALETTES.monoBlack, "flip"),
      b.location(PALETTES.monoBlack, "The Grand Ballroom"),
      b.timeline(PALETTES.monoBlack, debutTimeline),
      b.entourage(PALETTES.monoBlack, "roses", "18 Roses"),
      b.entourage(PALETTES.monoBlack, "candles", "18 Candles"),
      b.entourage(PALETTES.monoBlack, "treasures", "18 Treasures"),
      b.entourage(PALETTES.monoBlack, "blue_bills", "18 Blue Bills"),
      b.gallery(PALETTES.monoBlack, 3),
      b.dressCode(PALETTES.monoBlack, [{ hex: "#000000", name: "Black" }, { hex: "#FFFFFF", name: "White" }], "Formal Black & White"),
      b.faq(PALETTES.monoBlack),
      b.rsvp(PALETTES.monoBlack),
    ],
  }),
  defineTemplate({
    id: "debut-ivory-romance",
    name: "Ivory Romance",
    category: "debut",
    description: "Soft ivory palette with floral separators and intimate timeline.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "Sweet Eighteen", "A celebration of becoming"),
      b.separator(PALETTES.ivory, "floral"),
      b.message(PALETTES.ivory, "With grateful heart, I invite you to my debut."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, debutTimeline),
      b.entourage(PALETTES.ivory, "roses", "18 Roses"),
      b.entourage(PALETTES.ivory, "candles", "18 Candles"),
      b.gallery(PALETTES.ivory, 3),
      b.dressCode(PALETTES.ivory, [{ hex: "#f6f1ea", name: "Ivory" }, { hex: "#c9b9a4", name: "Champagne" }]),
      b.giftRegistry(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "debut-midnight-gala",
    name: "Midnight Gala",
    category: "debut",
    description: "Dark, cinematic debut with hero video and flip countdown.",
    palette: PALETTES.midnight,
    featured: true,
    blocks: [
      b.heroVideo(PALETTES.midnight, "Midnight Debut", "An evening under the stars"),
      b.message(PALETTES.midnight, "Tonight, I step into a new chapter."),
      b.countdown(PALETTES.midnight, "flip"),
      b.location(PALETTES.midnight),
      b.timeline(PALETTES.midnight, debutTimeline),
      b.entourage(PALETTES.midnight, "roses", "18 Roses"),
      b.entourage(PALETTES.midnight, "candles", "18 Candles"),
      b.entourage(PALETTES.midnight, "treasures", "18 Treasures"),
      b.gallery(PALETTES.midnight, 3),
      b.music(PALETTES.midnight),
      b.rsvp(PALETTES.midnight),
    ],
  }),
  defineTemplate({
    id: "debut-pearl-classic",
    name: "Pearl Classic",
    category: "debut",
    description: "Pearl white with serif typography and traditional program.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "My Debut", "Eighteen and grateful"),
      b.message(PALETTES.pearl, "Together with my parents, I invite you to celebrate."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl),
      b.timeline(PALETTES.pearl, debutTimeline),
      b.entourage(PALETTES.pearl, "roses", "18 Roses"),
      b.entourage(PALETTES.pearl, "candles", "18 Candles"),
      b.entourage(PALETTES.pearl, "treasures", "18 Treasures"),
      b.entourage(PALETTES.pearl, "blue_bills", "18 Blue Bills"),
      b.dressCode(PALETTES.pearl, [{ hex: "#fafaf7", name: "Pearl" }]),
      b.faq(PALETTES.pearl),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "debut-blush-garden",
    name: "Blush Garden",
    category: "debut",
    description: "Romantic blush tones with floral motifs and gallery focus.",
    palette: PALETTES.blush,
    blocks: [
      b.cover(PALETTES.blush, "Garden Debut", "Bloom into eighteen"),
      b.separator(PALETTES.blush, "hearts"),
      b.message(PALETTES.blush, "An afternoon of flowers, music, and memory."),
      b.countdown(PALETTES.blush),
      b.location(PALETTES.blush),
      b.gallery(PALETTES.blush, 3),
      b.entourage(PALETTES.blush, "roses", "18 Roses"),
      b.entourage(PALETTES.blush, "candles", "18 Candles"),
      b.dressCode(PALETTES.blush, [{ hex: "#f5e6e0", name: "Blush" }, { hex: "#d4a5a5", name: "Rose" }]),
      b.giftRegistry(PALETTES.blush),
      b.rsvp(PALETTES.blush),
    ],
  }),
  defineTemplate({
    id: "debut-charcoal-modern",
    name: "Charcoal Modern",
    category: "debut",
    description: "Modern editorial layout with bold marquee and minimal palette.",
    palette: PALETTES.charcoal,
    blocks: [
      b.cover(PALETTES.charcoal, "Debut · 18", "A modern celebration"),
      b.marquee(PALETTES.charcoal, "★ MY DEBUT ★ EIGHTEEN ★ FOREVER ★"),
      b.message(PALETTES.charcoal, "Less is more. Join me for an intimate evening."),
      b.countdown(PALETTES.charcoal, "flip"),
      b.location(PALETTES.charcoal),
      b.timeline(PALETTES.charcoal, debutTimeline),
      b.entourage(PALETTES.charcoal, "roses", "18 Roses"),
      b.entourage(PALETTES.charcoal, "candles", "18 Candles"),
      b.gallery(PALETTES.charcoal, 2),
      b.rsvp(PALETTES.charcoal),
    ],
  }),
  defineTemplate({
    id: "debut-sage-botanical",
    name: "Sage Botanical",
    category: "debut",
    description: "Earthy sage palette with botanical separators.",
    palette: PALETTES.sage,
    blocks: [
      b.cover(PALETTES.sage, "Eighteen", "A botanical debut"),
      b.separator(PALETTES.sage, "floral"),
      b.message(PALETTES.sage, "Among the leaves, we celebrate."),
      b.countdown(PALETTES.sage),
      b.location(PALETTES.sage),
      b.timeline(PALETTES.sage, debutTimeline),
      b.entourage(PALETTES.sage, "roses", "18 Roses"),
      b.entourage(PALETTES.sage, "candles", "18 Candles"),
      b.entourage(PALETTES.sage, "treasures", "18 Treasures"),
      b.dressCode(PALETTES.sage, [{ hex: "#e8ece4", name: "Sage" }, { hex: "#7a8b6f", name: "Olive" }]),
      b.gallery(PALETTES.sage, 3),
      b.rsvp(PALETTES.sage),
    ],
  }),
  defineTemplate({
    id: "debut-mono-white-minimal",
    name: "White Minimal",
    category: "debut",
    description: "Pure minimalism — only the essentials, beautifully arranged.",
    palette: PALETTES.monoWhite,
    blocks: [
      b.cover(PALETTES.monoWhite, "Debut", "18"),
      b.text(PALETTES.monoWhite, "An intimate gathering. Black tie."),
      b.countdown(PALETTES.monoWhite, "minimal"),
      b.location(PALETTES.monoWhite),
      b.entourage(PALETTES.monoWhite, "roses", "18 Roses"),
      b.entourage(PALETTES.monoWhite, "candles", "18 Candles"),
      b.dressCode(PALETTES.monoWhite, [{ hex: "#000000", name: "Black Tie" }]),
      b.rsvp(PALETTES.monoWhite),
    ],
  }),
  defineTemplate({
    id: "debut-storybook",
    name: "Storybook",
    category: "debut",
    description: "Tells the story of becoming through quotes, photos, and timeline.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "My Story", "Chapter Eighteen"),
      b.quote(PALETTES.ivory, "And so the adventure begins.", "—"),
      b.gallery(PALETTES.ivory, 2),
      b.message(PALETTES.ivory, "From childhood to today, every moment led here."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory),
      b.timeline(PALETTES.ivory, debutTimeline),
      b.entourage(PALETTES.ivory, "roses", "18 Roses"),
      b.entourage(PALETTES.ivory, "candles", "18 Candles"),
      b.entourage(PALETTES.ivory, "treasures", "18 Treasures"),
      b.faq(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "debut-cinematic",
    name: "Cinematic",
    category: "debut",
    description: "Video-first hero, music player, and immersive scroll.",
    palette: PALETTES.midnight,
    blocks: [
      b.heroVideo(PALETTES.midnight, "The Debut", "Press play"),
      b.music(PALETTES.midnight, "Theme Song"),
      b.message(PALETTES.midnight, "An evening designed like a film."),
      b.countdown(PALETTES.midnight, "flip"),
      b.location(PALETTES.midnight),
      b.timeline(PALETTES.midnight, debutTimeline),
      b.entourage(PALETTES.midnight, "roses", "18 Roses"),
      b.entourage(PALETTES.midnight, "candles", "18 Candles"),
      b.gallery(PALETTES.midnight, 3),
      b.socials(PALETTES.midnight),
      b.qr(PALETTES.midnight, "Share my debut"),
      b.rsvp(PALETTES.midnight),
    ],
  }),
];
