import { b, PALETTES, defineTemplate } from "../builder";
import type { TemplateDef } from "../types";

const weddingTimeline = [
  { time: "2:30 PM", title: "Guest Arrival", description: "" },
  { time: "3:00 PM", title: "Ceremony", description: "" },
  { time: "4:00 PM", title: "Cocktail Hour", description: "" },
  { time: "5:30 PM", title: "Reception & Dinner", description: "" },
  { time: "7:00 PM", title: "First Dance", description: "" },
  { time: "8:00 PM", title: "Party", description: "" },
];

export const weddingTemplates: TemplateDef[] = [
  defineTemplate({
    id: "wed-classic-ivory",
    name: "Classic Ivory",
    category: "wedding",
    featured: true,
    description: "Timeless ivory wedding with full ceremony, reception, and gift registry.",
    palette: PALETTES.ivory,
    blocks: [
      b.cover(PALETTES.ivory, "We're Getting Married", "Together with our families"),
      b.message(PALETTES.ivory, "Together with our families, we invite you to share in our joy."),
      b.countdown(PALETTES.ivory),
      b.location(PALETTES.ivory, "Ceremony Venue"),
      b.timeline(PALETTES.ivory, weddingTimeline),
      b.dressCode(PALETTES.ivory, [{ hex: "#f6f1ea", name: "Ivory" }, { hex: "#c9b9a4", name: "Champagne" }], "Semi-formal"),
      b.gallery(PALETTES.ivory, 3),
      b.giftRegistry(PALETTES.ivory),
      b.faq(PALETTES.ivory),
      b.rsvp(PALETTES.ivory),
    ],
  }),
  defineTemplate({
    id: "wed-mono-elopement",
    name: "Monochrome Elopement",
    category: "wedding",
    description: "Intimate, minimal black & white wedding announcement.",
    palette: PALETTES.monoBlack,
    blocks: [
      b.cover(PALETTES.monoBlack, "We Said Yes", "Save the date"),
      b.text(PALETTES.monoBlack, "An intimate ceremony. Just family and closest friends."),
      b.countdown(PALETTES.monoBlack, "flip"),
      b.location(PALETTES.monoBlack),
      b.dressCode(PALETTES.monoBlack, [{ hex: "#000000", name: "Black" }]),
      b.rsvp(PALETTES.monoBlack),
    ],
  }),
  defineTemplate({
    id: "wed-garden-blush",
    name: "Garden Blush",
    category: "wedding",
    featured: true,
    description: "Outdoor garden wedding with floral motifs and gallery.",
    palette: PALETTES.blush,
    blocks: [
      b.cover(PALETTES.blush, "Our Wedding Day", "Among the flowers"),
      b.separator(PALETTES.blush, "floral"),
      b.message(PALETTES.blush, "Join us in a garden of memories."),
      b.countdown(PALETTES.blush),
      b.location(PALETTES.blush),
      b.timeline(PALETTES.blush, weddingTimeline),
      b.gallery(PALETTES.blush, 3),
      b.dressCode(PALETTES.blush, [{ hex: "#f5e6e0", name: "Blush" }, { hex: "#9caf88", name: "Sage" }]),
      b.giftRegistry(PALETTES.blush),
      b.rsvp(PALETTES.blush),
    ],
  }),
  defineTemplate({
    id: "wed-midnight-romance",
    name: "Midnight Romance",
    category: "wedding",
    description: "Evening wedding with starlit hero video and music.",
    palette: PALETTES.midnight,
    blocks: [
      b.heroVideo(PALETTES.midnight, "We Do", "Under the stars"),
      b.music(PALETTES.midnight, "Our Song"),
      b.message(PALETTES.midnight, "Tonight begins forever."),
      b.countdown(PALETTES.midnight, "flip"),
      b.location(PALETTES.midnight),
      b.timeline(PALETTES.midnight, weddingTimeline),
      b.gallery(PALETTES.midnight, 3),
      b.dressCode(PALETTES.midnight, [{ hex: "#0d1424", name: "Midnight" }]),
      b.rsvp(PALETTES.midnight),
    ],
  }),
  defineTemplate({
    id: "wed-pearl-formal",
    name: "Pearl Formal",
    category: "wedding",
    description: "Traditional cathedral-style wedding with full program.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "Holy Matrimony", "We invite you to witness our union"),
      b.quote(PALETTES.pearl, "Two hearts, one promise."),
      b.message(PALETTES.pearl, "We humbly request the honor of your presence."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl, "Cathedral"),
      b.timeline(PALETTES.pearl, weddingTimeline),
      b.dressCode(PALETTES.pearl, [{ hex: "#fafaf7", name: "Pearl" }]),
      b.giftRegistry(PALETTES.pearl),
      b.faq(PALETTES.pearl),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "wed-sage-rustic",
    name: "Sage Rustic",
    category: "wedding",
    description: "Barn / rustic vibe with botanical sage tones.",
    palette: PALETTES.sage,
    blocks: [
      b.cover(PALETTES.sage, "Rustic Wedding", "In the countryside"),
      b.separator(PALETTES.sage, "wave"),
      b.message(PALETTES.sage, "Boots, lights, and love."),
      b.countdown(PALETTES.sage),
      b.location(PALETTES.sage, "The Old Barn"),
      b.timeline(PALETTES.sage, weddingTimeline),
      b.gallery(PALETTES.sage, 3),
      b.dressCode(PALETTES.sage, [{ hex: "#7a8b6f", name: "Sage" }, { hex: "#c9b9a4", name: "Wheat" }]),
      b.giftRegistry(PALETTES.sage),
      b.rsvp(PALETTES.sage),
    ],
  }),
  defineTemplate({
    id: "wed-charcoal-modern",
    name: "Modern Editorial",
    category: "wedding",
    description: "Editorial-style wedding with bold typography and minimal flourish.",
    palette: PALETTES.charcoal,
    blocks: [
      b.cover(PALETTES.charcoal, "WED", "—"),
      b.marquee(PALETTES.charcoal, "★ FOREVER ★ TOGETHER ★ ALWAYS ★"),
      b.message(PALETTES.charcoal, "A modern celebration of love."),
      b.countdown(PALETTES.charcoal, "flip"),
      b.location(PALETTES.charcoal),
      b.timeline(PALETTES.charcoal, weddingTimeline),
      b.gallery(PALETTES.charcoal, 2),
      b.rsvp(PALETTES.charcoal),
    ],
  }),
  defineTemplate({
    id: "wed-beach-getaway",
    name: "Beach Getaway",
    category: "wedding",
    description: "Destination beach wedding with travel info and FAQ.",
    palette: PALETTES.pearl,
    blocks: [
      b.cover(PALETTES.pearl, "Beach Wedding", "Toes in the sand"),
      b.separator(PALETTES.pearl, "wave"),
      b.message(PALETTES.pearl, "Pack your sunscreen and your dancing shoes."),
      b.countdown(PALETTES.pearl),
      b.location(PALETTES.pearl, "Beachfront Resort"),
      b.timeline(PALETTES.pearl, weddingTimeline),
      b.dressCode(PALETTES.pearl, [{ hex: "#e8ece4", name: "Sandstone" }, { hex: "#7aa9b5", name: "Ocean" }], "Beach formal"),
      b.gallery(PALETTES.pearl, 3),
      b.faq(PALETTES.pearl),
      b.giftRegistry(PALETTES.pearl),
      b.rsvp(PALETTES.pearl),
    ],
  }),
  defineTemplate({
    id: "wed-cinematic-story",
    name: "Cinematic Story",
    category: "wedding",
    description: "Their love story told page by page with imagery.",
    palette: PALETTES.midnight,
    blocks: [
      b.heroVideo(PALETTES.midnight, "Our Story", "How we got here"),
      b.gallery(PALETTES.midnight, 3),
      b.quote(PALETTES.midnight, "We met. We fell. We're forever."),
      b.message(PALETTES.midnight, "From a chance meeting to forever."),
      b.countdown(PALETTES.midnight, "flip"),
      b.location(PALETTES.midnight),
      b.timeline(PALETTES.midnight, weddingTimeline),
      b.music(PALETTES.midnight, "Our First Dance"),
      b.socials(PALETTES.midnight),
      b.rsvp(PALETTES.midnight),
    ],
  }),
  defineTemplate({
    id: "wed-mono-white-vow",
    name: "White Vow",
    category: "wedding",
    description: "Pure white minimalist wedding focused on the vows.",
    palette: PALETTES.monoWhite,
    blocks: [
      b.cover(PALETTES.monoWhite, "I Do", "Our vows"),
      b.quote(PALETTES.monoWhite, "I promise to love you in all your seasons."),
      b.text(PALETTES.monoWhite, "An intimate ceremony followed by dinner."),
      b.countdown(PALETTES.monoWhite, "minimal"),
      b.location(PALETTES.monoWhite),
      b.dressCode(PALETTES.monoWhite, [{ hex: "#ffffff", name: "All White" }]),
      b.rsvp(PALETTES.monoWhite),
    ],
  }),
];
